baseurl = "https://evdbogaard.nl/"
title = "Erwin van den Bogaard"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 15

[markup.highlight]
style = "github-dark"

[params]
  author = "Erwin van den Bogaard"
  #info = "Full Stack DevOps and Magician"
  description = "Erwin van den Bogaard's personal blogging website website"
  keywords = "blog,developer,personal,azure,c#"
  avatarurl = "images/Erwin_Part.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "images/Erwin_Part.png"
  favicon_16 = "images/Erwin_Part.png"

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/evdbogaard/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/erwinvandenbogaard/"
#[[params.social]]
#  name = "Twitter"
#  icon = "fa-brands fa-x-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"